---
title: "Enunciados de los problemas"
author: "Víctor Silva Nieves"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-location: left
    number-sections: true
    code-fold: false
    theme:
      - cosmo
      - estilo/tema.scss
  typst: 
    toc: true
    number-sections: true
    include-before-body: estilo/toc-sep.typ
    code-fold: false
    brand: _brand.yml
lang: es
---

## Problema 1

Se deben implementar todos los métodos de decisión bajo incertidumbre, tanto para el caso favorable como para el caso desfavorable (pesimista, optimista, Hurwicz, Savage, Laplace y punto ideal) para la siguiente tabla de decisión:

|       | $\omega_1$ | $\omega_2$ | $\omega_3$ | $\omega_4$ |
|-------|------------|------------|------------|------------|
| $a_1$ | 5          | 15         | 8          | 18         |
| $a_2$ | 7          | 13         | 14         | 20         |
| $a_3$ | 6          | 17         | 11         | 17         |
| $a_4$ | 4          | 14         | 16         | 16         |
| $a_5$ | 10         | 10         | 13         | 15         |

## Problema 2

Una persona recibe una herencia de 200.000 euros y se le presentan diferentes opciones de inversión para los próximos 10 años.

Puede terminar de pagar su hipoteca actual, ahorrando 40.000 euros de intereses y le sobrarían 30.000 euros que pondría en una cuenta remunerada al 2% anual

Puede seguir pagando su hipoteca y elegir una de las siguientes opciones

* Adquirir un piso por esa cantidad y si los alquileres turísticos siguen siendo posibles podrá generar un 6% anual. Si por el contrario se regularan pasaría a perder un 1% anual.
* Invertir en un fondo indexado que le puede generar un 7% anual pero si la bolsa baja perderá un 8%.
* Invertir en una franquicia de una cadena de comida rápida. Si acierta con el sitio podrá generar un 10% anual pero si se equivoca al seleccionar el sitio incurrirá en unas pérdidas anuales del 10%
